# Generated by Django 3.2.7 on 2021-09-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_categoria_variacion'),
        ('cart', '0003_cartitem_variaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variaciones',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
